---

# Set Juniper switch login banner

- hosts: all
  gather_facts: false
  connection: local

#variables should be defined in the template
  vars:

  tasks:
  - name: configure the login banner
    junos_banner:
      banner: login
      text: "{{login_banner}}"
      state: present


...
