---
#Create a new VM with OS from a template
- hosts: all
  gather_facts: false
  connection: local

#variables should be defined in the template
  vars:


  tasks:
  # get date
  - set_fact: creationdate="{{lookup('pipe','date "+%Y/%m/%d %H:%M"')}}"

  # Create VM from a template
  - name: create VM
    vmware_guest:
      validate_certs: no
      hostname: "{{ vcenter }}"
      datacenter: "{{ datacenter }}"
      name: "{{ vm_name }}"
      template: "{{ template }}"
      state: poweredon
      extra_config:
        vcpu.hotadd: yes
        mem.hotadd:  yes
        notes: "{{ notes }} - {{ creationdate }}"
      disk:
        size_gb: 50
        type: thin
        datastore: "{{ datastore }}"
      hardware:
        memory_mb: "{{ vm_memory_mb }}"
        num_cpus: "{{ vm_cpu }}"
        scsi: paravirtual
        osid: RHEL64Guest
      vm_nic:
        nic1:
          type: vmxnet3
          network: "{{port_group}}"
          network_type: standard
#      networks:
#        vm_ip: "{{vm_ip}}"
#        gateway: "{{vm_gateway}}"
#        netmask: "{{vm_netmask}}"

        wait_for_ip_address: yes
# Add new VM to list of host in Ansible
  - name: add to ansible hosts file
    lineinfile:
      dest: /etc/ansible/hosts
      insertafter: '^\[{{ ansible_host_group }}\]'
    run_once: true
...
