---

# Set ESXi hosts vSwitch configuration
- hosts: all
  gather_facts: false
  connection: local

#variables should be defined in the template
#  vars:

  tasks:
  - name: Add a VMWare vSwitch with multiple NICs
    vmware_vswitch:
      switch: "{{virtual-switch-name}}"
      nics:
      - "{{virtual-switch-vmnic1}}"
      - "{{virtual-switch-vmnic1}}"
      mtu: 9000
      delegate_to: localhost

...
