---

# Set ESXi host DNS configuration
- hosts: all
  gather_facts: false

#variables should be defined in the template
#  var:

  tasks:
  - name: Configure ESXi hostname and DNS server
    local_action:
      module: vmware_dns_config
      domainname: "{{domain_name}}"
      dns_servers:
        - "{{dns1}}"
        - "{{dns2}}"

...
